--- 
externalDocs: 
  description: "Find out more about OVE"
  url: "https://dsi.gitbook.io/ove"
paths: 
  /operation/bufferStatus: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
          schema: 
            properties: 
              status: 
                enum: 
                  - complete
                  - buffering
                type: string
            type: object
      summary: "Reads the buffer status of one or all audio"
      tags: 
        - operation
  /operation/mute: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "Mutes playback one or all audio files"
      tags: 
        - operation
  /operation/pause: 
    get: 
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "Pauses playback on one or all audio"
      tags: 
        - operation
  /operation/play: 
    get: 
      parameters: 
        - 
          description: "Loop playback or not"
          enum: 
            - "true"
            - "false"
          in: query
          name: loop
          required: false
          type: string
        - 
          description: "volume to play at"
          in: query
          name: volume
          required: false
          type: float
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "Plays one or all audio files"
      tags: 
        - operation
  /operation/seekTo: 
    get: 
      parameters: 
        - 
          description: "Time in seconds from start of video"
          format: float
          in: query
          name: time
          required: true
          type: number
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "Seeks to a specific time one or all audio files"
      tags: 
        - operation
  /operation/setPosition: 
    get: 
      parameters: 
        - 
          description: "x value"
          format: float
          in: query
          name: x
          required: true
          type: number
        - 
          description: "y value"
          format: float
          in: query
          name: "y"
          required: true
          type: number
        - 
          description: "z value"
          format: float
          in: query
          name: z
          required: true
          type: number
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "sets the positional audio in 3d space for one or all audio files"
      tags: 
        - operation
  /operation/setVolume: 
    get: 
      parameters: 
        - 
          description: "Volume level between 0 and 1.0"
          format: float
          in: query
          name: volume
          required: true
          type: number
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "sets the volume level for one or all audio files"
      tags: 
        - operation
  /operation/stop: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "Stops playback one or all audio files and resets time to the start"
      tags: 
        - operation
  /operation/unmute: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "unutes playback one or all audio files"
      tags: 
        - operation
  /operation/volDown: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "decreases volume in one or all audio files"
      tags: 
        - operation
  /operation/volUp: 
    get: 
      parameters: 
        - 
          description: "Section ID"
          format: int32
          in: query
          name: oveSectionId
          required: false
          type: integer
      produces: 
        - application/json
      responses: 
        200: 
          description: "successful operation"
      summary: "increases volume in one or all audio files"
      tags: 
        - operation
tags: 
  - 
    description: "Operations that can be performed on one or all audio"
    name: operation
